;;; GNU Guix package definition for `copy`.
;;;
;;; Guix builds are hermetic (no network), so the crate dependencies must be
;;; supplied at build time. Rather than packaging every transitive crate, this
;;; definition builds against a locally vendored copy of the dependencies.
;;;
;;; One-time prep, then build:
;;;
;;;   cargo vendor guix/vendor      # writes the crate sources (gitignored)
;;;   guix build -f guix.scm
;;;   guix shell -f guix.scm        # drop the binary into an environment
;;;
;;; The vendored directory is injected as a store item and cargo is pointed at
;;; it via .cargo/config.toml, so the build stays offline.
;;;
;;; Note: edition 2024 needs rustc >= 1.85; ensure your Guix `rust` is new
;;; enough. To build with SELinux xattr support, add `libselinux` to inputs and
;;; append "--features" "selinux-support" to the cargo invocation below.

(use-modules (guix packages)
             (guix gexp)
             (guix git-download)
             (guix build-system gnu)
             (gnu packages rust)
             ((guix licenses) #:prefix license:))

(define %vendor
  ;; Generated by `cargo vendor guix/vendor` (see header). Evaluating this file
  ;; before that directory exists is expected to fail.
  (local-file "guix/vendor" "copy-vendor" #:recursive? #t))

(package
  (name "copy")
  (version "0.1.4")                     ; keep in sync with Cargo.toml
  (source (local-file "." "copy-checkout"
                      #:recursive? #t
                      ;; Only tracked files — drops target/, result, .git and
                      ;; the untracked guix/vendor (supplied separately above).
                      #:select? (git-predicate (dirname (current-filename)))))
  (build-system gnu-build-system)
  (arguments
   (list
    #:phases
    #~(modify-phases %standard-phases
        (delete 'configure)
        (delete 'check)                 ; tests run via `cargo test` / CI
        (replace 'build
          (lambda _
            (setenv "CARGO_HOME" (string-append (getcwd) "/.cargo-home"))
            (setenv "CARGO_NET_OFFLINE" "true")
            (mkdir-p ".cargo")
            (call-with-output-file ".cargo/config.toml"
              (lambda (port)
                (format port "\
[source.crates-io]
replace-with = \"vendored-sources\"

[source.vendored-sources]
directory = ~s~%" #$%vendor)))
            (invoke "cargo" "build" "--release" "--frozen" "--offline")))
        (replace 'install
          (lambda _
            (install-file "target/release/copy"
                          (string-append #$output "/bin"))
            (install-file "LICENSE"
                          (string-append #$output "/share/licenses/copy")))))))
  (native-inputs (list rust (list rust "cargo")))
  (home-page "https://github.com/UnbreakableMJ/copy")
  (synopsis "A modern, fast file copying tool")
  (description
   "copy is a modern, parallel replacement for the @command{cp} command on
Linux.  It copies files and directories in parallel with progress bars, can
resume interrupted transfers, preserves attributes, and supports reflink and
gitignore-style exclude patterns.")
  (license license:expat))
