version = 1

[[annotations]]
path = [
  "src/**/*.rs",
  "tests/**/*.rs",
]
precedence = "aggregate"
SPDX-FileCopyrightText = [
  "2026 Bhuminjay Soni",
  "2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>",
]
SPDX-License-Identifier = "MIT AND GPL-3.0-or-later"

[[annotations]]
path = [
  "Cargo.toml",
  "rustfmt.toml",
  "flake.nix",
  "nix/*.nix",
  "guix.scm",
  "packaging/aur/PKGBUILD",
  "install.sh",
  "benchmarks/*.sh",
  "tests/gnu/*.sh",
  ".github/workflows/*.yml",
  ".gitignore",
  "packaging/aur/.SRCINFO",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
  "CLAUDE.md",
  "README.md",
  "README_CRATES.md",
  "CONTRIBUTING.md",
  "docs/*.md",
  "benchmarks/*.md",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
  "LICENSE",
  "LICENSES/GPL-3.0-or-later.txt",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Free Software Foundation, Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "LICENSES/MIT.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Bhuminjay Soni"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "flake.lock",
  "Cargo.lock",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
